### ISSUE TITLE
Thread for task 1-read-pbf failed

### ISSUE THREAD

**Issue by stepankuzmin** [mapbox/osm-boundaries#12]
I've tried `./run.py -d osm_boundaries -f 2 -t 6 planet-latest.osm.pbf` but it failed with this:

``` shell
INFO: Pipeline executing, waiting for completion.
Apr 29, 2015 3:47:27 PM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-pbf failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Cannot represent 2312448328 as an integer.
        at org.openstreetmap.osmosis.core.util.LongAsInt.longToInt(LongAsInt.java:33)
        at org.openstreetmap.osmosis.core.filter.common.ListIdTracker.set(ListIdTracker.java:118)
        at org.openstreetmap.osmosis.tagfilter.v0_6.UsedNodeFilter.process(UsedNodeFilter.java:96)
        at org.openstreetmap.osmosis.core.container.v0_6.WayContainer.process(WayContainer.java:60)
        at org.openstreetmap.osmosis.tagfilter.v0_6.UsedNodeFilter.process(UsedNodeFilter.java:65)
        at org.openstreetmap.osmosis.tagfilter.v0_6.UsedWayFilter.complete(UsedWayFilter.java:131)
        at org.openstreetmap.osmosis.tagfilter.v0_6.TagFilter.complete(TagFilter.java:142)
        at org.openstreetmap.osmosis.tagfilter.v0_6.TagFilter.complete(TagFilter.java:142)
        at crosby.binary.osmosis.OsmosisBinaryParser.complete(OsmosisBinaryParser.java:35)
        at crosby.binary.file.BlockInputStream.process(Unknown Source)
        at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:37)
        at java.lang.Thread.run(Thread.java:745)

Apr 29, 2015 3:47:27 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:328)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:31)
```

Table `carto_boundary` is empty.

Ubuntu 14.04.2 LTS
python-psycopg2
osmosis 0.40.1
PostgreSQL 9.3
PostGIS 2.1
osmium 0.0~20111213-g7f3500a-3build5

**Comment by stepankuzmin** [comment]
Mea culpa, I use old osmosis version. Closing issue.
