### ISSUE TITLE
run.py fails at osmosis due to unknown error

### ISSUE THREAD

**Issue by dkerkow** [mapbox/osm-boundaries#7]
When running run.py, I get the following error in the osmosis part:

``` bash
SCHWERWIEGEND: Thread for task 1-read-pbf failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Cannot represent 2191925799 as an integer.
    at org.openstreetmap.osmosis.core.util.LongAsInt.longToInt(LongAsInt.java:33)
    at org.openstreetmap.osmosis.core.filter.common.ListIdTracker.set(ListIdTracker.java:118)
    at org.openstreetmap.osmosis.tagfilter.v0_6.UsedNodeFilter.process(UsedNodeFilter.java:96)
    at org.openstreetmap.osmosis.core.container.v0_6.WayContainer.process(WayContainer.java:60)
    at org.openstreetmap.osmosis.tagfilter.v0_6.UsedNodeFilter.process(UsedNodeFilter.java:65)
    at org.openstreetmap.osmosis.tagfilter.v0_6.UsedWayFilter.complete(UsedWayFilter.java:131)
    at org.openstreetmap.osmosis.tagfilter.v0_6.TagFilter.complete(TagFilter.java:142)
    at org.openstreetmap.osmosis.tagfilter.v0_6.TagFilter.complete(TagFilter.java:142)
    at crosby.binary.osmosis.OsmosisBinaryParser.complete(OsmosisBinaryParser.java:35)
    at crosby.binary.file.BlockInputStream.process(Unknown Source)
    at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:37)
    at java.lang.Thread.run(Thread.java:679)
14.03.2013 12:03:29 org.openstreetmap.osmosis.core.Osmosis main
SCHWERWIEGEND: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
    at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
    at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
    at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:328)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:31)
```

**Comment by ajashton** [comment]
You need to update osmosis to version 0.42 to get 64-bit integer support.

http://bretth.dev.openstreetmap.org/osmosis-build/
